version: "3.7"
services:
  go:
    build:
      context: ./
      dockerfile: ./build/docker/go/Dockerfile
    environment:
      OWNER_NAME: ${OWNER_NAME}
      PROJECT_NAME: ${PROJECT_NAME_GO}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - .:/go/src/${OWNER_NAME}/${PROJECT_NAME_GO}
    working_dir: /go/src/${OWNER_NAME}/${PROJECT_NAME_GO}
    command: make build

  sam:
    build:
      context: ./build/docker/sam
    volumes:
      - .:/opt/sam
    working_dir: /opt/sam
    environment:
      SAM_CLI_TELEMETRY: 0 # see: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html
      PROJECT_NAME: ${PROJECT_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
